<?php 
/**
* @version		$Id: hosts.php 422 2011-06-21 20:47:54Z datahell $
* @package		Elxis
* @subpackage	Elxis Defender
* @copyright	Copyright (c) 2006-2012 Elxis CMS (http://www.elxis.org). All rights reserved.
* @license		Elxis Public License ( http://www.elxis.org/elxis-public-license.html )
* @author		Elxis Team ( http://www.elxis.org )
* @description 	Elxis CMS is free software. Read the license for copyright notices and details
*/

defined('_ELXIS_') or die ('Direct access to this location is not allowed.');


/* HOSTS (Last update: 2011-06-21 20:50:10) */
$signatures = array(
	array('inmatch', 'hoster', 'hosteurope', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'seomoz.org', 'Site scrapers.'),
	array('rmatch', 'hoster', 'rulinki.ru', 'Bad spider, does not use robots.txt.'),
	array('rmatch', 'hoster', 'internetserviceteam.com', 'internetserviceteam, phpbb hackers.'),
	array('rmatch', 'hoster', 'kimsufi.com', 'kimsufi, forum spambots.'),
	array('rmatch', 'hoster', 'pool.ukrtel.net', 'ukrtel, forum spambots.'),
	array('rmatch', 'hoster', 'mbox.kz', 'mbox, blog sploit bothost.'),
	array('rmatch', 'hoster', 'cjh-law.com', 'cjh-law, nasty phishers / scammers.'),
	array('rmatch', 'hoster', 'kiyosho.jp', 'kiyosho, infected japanese machine.'),
	array('rmatch', 'hoster', 'adsinmedia.co.in', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', '.dreamhost.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'holhost.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'vip-net.pl', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', '23gb.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'swifttrim.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'hotchilli.net', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'dns-safe.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'cadinor.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'neointeractiva.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', '3fn.net', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', '.fsfreeware.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'linkneo.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'host.caracastelecom.net', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'ig.com.br', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'clanmoi.de', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'piemontetv.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'authenticnetworks.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'ogicom.pl', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'agava.net', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'rivreg.ru', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'americanforeclosures.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'vampire.pl', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'midphase.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'brasiltelecom.net.br', 'Bothost and/or Server Farm (credit: eclecticdjs.com).'),
	array('rmatch', 'hoster', 'starnet.md', 'Bothost and/or Server Farm (credit: eclecticdjs.com).'),
	array('rmatch', 'hoster', 'steephost.com', 'Bothost and/or Server Farm (credit: eclecticdjs.com).'),
	array('rmatch', 'hoster', 'followmeoffice.com', 'Bothost / Better idea, dont follow me.'),
	array('rmatch', 'hoster', 'dumpyourbitch.com', 'Rude script attackers.'),
	array('rmatch', 'hoster', 'exatt.net', 'Bad ISP, allows bots to run loose, hides fact its in Mumbai, India.'),
	array('rmatch', 'hoster', 'dotnetdotcom.org', 'Bad search spider. Ignores robots.txt. Offers an explosive .zip to those who try to use their services.'),
	array('rmatch', 'hoster', 'asianet.co.th', 'Bothost / Fake ISP.'),
	array('rmatch', 'hoster', 'veloxzone.com.br', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'qvt.net.br', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'vtr.net', 'Bothost and/or Server Farm (weird!).'),
	array('rmatch', 'hoster', 'terra.cl', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', '.net.co', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'iam.net.ma', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', '35up.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'netvision.net.il', 'ISP with a filthy reputation.'),
	array('rmatch', 'hoster', 'isnet.net', 'South African Bothosts.'),
	array('rmatch', 'hoster', 'tiscali.it', 'tiscali, constant source of forum spam attempts.'),
	array('rmatch', 'hoster', 'dragonara.net', 'Spamjockey ISP... GO AWAY!.'),
	array('rmatch', 'hoster', 'accentrainc.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'colo.iinet.com', 'Iterasi site scrapers.'),
	array('rmatch', 'hoster', 'smartservercontrol.com', 'smartservercontrol.com - ya aint controlling my server bub.'),
	array('rmatch', 'hoster', 'hinet.net', 'Ridin dirty Chinese ISP.'),
	array('rmatch', 'hoster', 'chello.pl', 'Filthy ISP/Host, constant source of attacks.'),
	array('rmatch', 'hoster', 'accelovation.com', 'Content scraper for paid service.'),
	array('rmatch', 'hoster', 'setooz.com', 'Email harvester from India.'),
	array('rmatch', 'hoster', 'altushost.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'bestprice.com', 'Spammers.'),
	array('rmatch', 'hoster', 'doctore.sk', 'Skiddy.'),
	array('rmatch', 'hoster', 'privatedns.com', 'No www site, and several attacks.'),
	array('rmatch', 'hoster', 'page-store.com', 'SEOMOZ keyword scraper.'),
	array('rmatch', 'hoster', 'mantraonline.com', 'Indian spammers / malware spreaders.'),
	array('rmatch', 'hoster', 'jkserv.net', 'Game server network that keeps probing the author.'),
	array('rmatch', 'hoster', 'webhostserver.biz', 'Server network that keeps probing the author.'),
	array('rmatch', 'hoster', 'slicehost.net', 'slicehost.net bothost.'),
	array('rmatch', 'hoster', 'ctinets.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'server4you.de', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'propagation.net', 'No propogation allowed (spammers).'),
	array('rmatch', 'hoster', 'hostacy.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'onlinehome-server.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'onlinehome-server.net', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'onlinehome-server.info', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'bezeqint.net', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'prking.com.au', 'Spammer.'),
	array('rmatch', 'hoster', '.server.de', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'nettopia.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'webfusion.co.uk', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'phatservers.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'insite.com.br', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'justhost.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'is74.ru', 'Proxy provider for hackers.'),
	array('inmatch', 'hoster', 'ecatel', 'Bothost and/or Server Farm.'),
	array('inmatch', 'hoster', '45ru.net.au', 'Abuse RFC ignorant network, caught abusing.'),
	array('rmatch', 'hoster', 'alicedsl.de', 'Scraper/Probe/listed on abuse.rfc-ignorant.org.'),
	array('rmatch', 'hoster', 'reliablehosting.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'quadranet.com', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'server.lu', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', 'ertelecom.ru', 'Bothost and/or Server Farm.'),
	array('rmatch', 'hoster', '.airtelbroadband.in', 'Malicious ISP, fostering spambots.'),
	array('rmatch', 'hoster', '.pldt.net', 'Malicious ISP, fostering spambots.'),
//Cloud Computing Providers
	array('rmatch', 'hoster', 'softlayer.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'newservers.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'savvis.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'terremark.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'gogrid.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'joyent.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'salesforce.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'rackspace.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'rackspacecloud.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'engineyard.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'heroku.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'rightscale.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '10gen.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '3leafsystems.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '3tera.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'appirio.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'appistry.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'appnexus.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'aptana.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'arjuna.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'asyanka.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'bluewolf.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'boomi.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.box.net', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'camsolutionsinc.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cassatt.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloud9analytics.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloudera.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloudcomputingchina.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloudscale.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloudstatus.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloudworks.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cohesiveft.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'theprocessfactory.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'dataline.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'datasisar.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'elastichosts.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'elastra.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.emc.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'enkiconsulting.net', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'enomalism.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'eucalyptus.cs.uscb.edu', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'flexiscale.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.force.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'fortressitx.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'g.ho.st', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'gigaspaces.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'thinkgos.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.hosting.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'hyperic.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'icloud.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'jumpbox.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'kaavo.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'keynote.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'layeredtech.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'mor.ph', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'morphexchange.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'nasstar.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'netsuite.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'nirvanix.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'nscaled.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'opennebula.org', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'qrimp.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'rightscale.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'stax.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'thoughtexpress.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'trustsaas.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'utilitystatus.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'moderro.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloud.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'hexagrid.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'nscaled.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'onelogin.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'qlayer.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'skytap.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'webscalesolutions.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'agathon.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.gridlayer.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.thegridlayer.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'reliacloud.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'mosso.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'newservers.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'pluraprocessing.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'azati.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'birtondemand.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'bungeeconnect.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloudcontrol.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'imodrive.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'novatium.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'quantix-uk.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '12designer.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'aconex.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'advologix.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'altornetworks.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'mturk.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'amitive.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'andersdenken.at', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.appian.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'appjet.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'apprenda.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'appzero.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'ariasystems.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'artofdefence.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'asterdata.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'beam4d.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'beowulf.org', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'bhivesoft.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'blinklogic.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'bluelock.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'bucketexplorer.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'caspio.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'castiron.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'clarioanalytics.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'clickability.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloud42.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloud9analytics.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloudera.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloudfoundry.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloudkick.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'cloudswitch.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'clusterseven.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'coghead.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'coldlightsolutions.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'collab.net', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'concur.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.ctera.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'datasynaps.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'directlaw.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'doclanding.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'dropbox.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'dynamsoft.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.dyn.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.emc.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'enstratus.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'etelos.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'eucalyptus.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'evapt.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'fathomdb.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'gemstone.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.gnip.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'hubspan.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.icims.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'iboss.org', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'infobright.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'informatica.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'itricityhosting.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'junglebox.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'k2analytics.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'knowledgetree.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'liveops.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'loadstorm.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'logixml.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'longjump.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'memcached.org', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'mozy.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'mulesoft.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'netapp.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'netdocuments.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'newrelic.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'nionex.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'oco-inc.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'onpathtech.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'controltier.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'openqrm.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'opsource.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.panorama.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.parallels.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'parascale.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'parature.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'pinqidentity.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'pivotlink.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'optimal.de', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'quantivo.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.quest.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'redi2.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'reductivelabs.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'responsys.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'rightnow.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'rollbase.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'rpath.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'sertifi.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'evionet.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'snaplogic.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'soasta.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'springcm.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'streetsmarts.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'successmetrics.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'symplified.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'syncplicity.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'taleo.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.terracotta.org', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'terramark.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '1978th.net', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'vaultscape.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'vertica.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'vmware.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.voda.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'vordel.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.voxel.net', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'webhosting.uk.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', '.workday.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'xactlycorp.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'xcalibre.co.uk', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'xen.org', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'xythos.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'zembly.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'zetta.net', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'zimory.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'zmanda.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'zoho.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'zuora.com', 'Cloud Services. Not an ISP.'),
	array('rmatch', 'hoster', 'retail.telecomitalia.it', 'Spammer tolerant host network.'),
	array('rmatch', 'hoster', 'fidelity.com', 'fidelity.c0m, Abusive forum scraping network.'),
	array('rmatch', 'hoster', 'technicolor.com', 'technicolor.c0m, Abusive forum scraping network.'),
	array('inmatch', 'hoster', 'ipredate', 'Skiddy friendly cloud services.'),
	array('inmatch', 'hoster', 'netdirekt', 'Notorious forums spammer'),
	array('inmatch', 'hoster', 'netdirect', 'Notorious forums spammer'),
	array('inmatch', 'hoster', 'internetserviceteam', 'Notorious forums spammer'),
	array('inmatch', 'hoster', 'jmhservices', 'Notorious forums spammer'),
	array('inmatch', 'hoster', 'keyserver', 'RBN.'),
	array('inmatch', 'hoster', 'keymachine', 'RBN.'),
	array('inmatch', 'hoster', 'keyweb', 'RBN.'),
	array('inmatch', 'hoster', 'oliro', 'RBN.'),
	array('inmatch', 'hoster', 'filmefashion', 'RBN.'),
	array('rmatch', 'hoster', 'idknet.com', 'RBN.'),
	array('rmatch', 'hoster', 'poltava.ua', 'RBN.'),
	array('rmatch', 'hoster', 'utel.net.ua', 'RBN.'),
	array('rmatch', 'hoster', 'infobox.ru', 'RBN.'),
	array('rmatch', 'hoster', 'infobox.org', 'RBN.'),
	array('rmatch', 'hoster', 'vdswin.com', 'RBN.'),
	array('rmatch', 'hoster', 'rbn.com.ua', 'RBN.'),
	array('rmatch', 'hoster', 'hc.ru', 'RBN.'),
	array('rmatch', 'hoster', 'telsp.net.br', 'RBN.'),
	array('rmatch', 'hoster', 'power-web34.net', 'RBN.'),
	array('rmatch', 'hoster', 'temka.biz', 'RBN.'),
	array('rmatch', 'hoster', 'dl-hosting.com', 'RBN.'),
	array('rmatch', 'hoster', 'tagdance.de', 'RBN.'),
	array('rmatch', 'hoster', 'efdns.de', 'RBN.'),
	array('rmatch', 'hoster', 'keyaccount.de', 'RBN.'),
	array('rmatch', 'hoster', 'ahost01.de', 'RBN.'),
	array('rmatch', 'hoster', 'em-zwo.de', 'RBN.'),
	array('rmatch', 'hoster', 'amplilogic.com', 'RBN.'),
	array('rmatch', 'hoster', 'creatoor.com', 'RBN.'),
	array('rmatch', 'hoster', 'x-svr.com', 'RBN.'),
	array('rmatch', 'hoster', 'keymars64.de', 'RBN.'),
	array('rmatch', 'hoster', 'haebdler-treff.de', 'RBN.'),
	array('rmatch', 'hoster', 'traders-briefing.de', 'RBN.'),
	array('rmatch', 'hoster', 'hosting-ie.com', 'RBN.'),
	array('rmatch', 'hoster', 'mail.adc.de', 'RBN.'),
	array('rmatch', 'hoster', 'ethymos.com.br', 'RBN.'),
	array('rmatch', 'hoster', 'softel.com.pl', 'RBN.'),
	array('rmatch', 'hoster', 'astranight.com', 'RBN.'),
	array('rmatch', 'hoster', 'ipilum.com', 'RBN.'),
	array('rmatch', 'hoster', 'vilitas.de', 'RBN.'),
	array('rmatch', 'hoster', 'rootbash.de', 'RBN.'),
	array('rmatch', 'hoster', 'securewebserver.de', 'RBN.'),
	array('rmatch', 'hoster', 'w-4.de', 'RBN.'),
	array('rmatch', 'hoster', 'corbina.ru', 'RBN.'),
	array('rmatch', 'hoster', 'prommorpg.com', 'RBN.'),
	array('rmatch', 'hoster', 'relan.ru', 'RBN.'),
	array('rmatch', 'hoster', 'volia.net', 'RBN.'),
	array('rmatch', 'hoster', 'yandex.ru', 'RBN.'),
	array('rmatch', 'hoster', 'dedibox.fr', 'RBN.'),
	array('rmatch', 'hoster', 'laycat.com', 'RBN.'),
	array('rmatch', 'hoster', 'kyklo.com', 'RBN.'),
	array('rmatch', 'hoster', 'aceleo.com', 'RBN.'),
	array('rmatch', 'hoster', 'majordomo.ru', 'RBN.'),
	array('rmatch', 'hoster', 'sovam.net.ua', 'RBN.'),
	array('rmatch', 'hoster', 'phatservers.com', 'RBN.'),
	array('rmatch', 'hoster', 'limt.ru', 'RBN.'),
	array('rmatch', 'hoster', 'netorn.ru', 'RBN.'),
	array('rmatch', 'hoster', 'netorn.net', 'RBN.'),
	array('rmatch', 'hoster', 'cpms.ru', 'RBN.'),
	array('rmatch', 'hoster', 'itns.ru', 'RBN.'),
	array('rmatch', 'hoster', 'kuzbass.net', 'RBN.'),
	array('rmatch', 'hoster', 'kemhost.net', 'RBN.'),
	array('rmatch', 'hoster', 'spb.ru', 'RBN.'),
	array('rmatch', 'hoster', 'elsv-v.ru', 'RBN.'),
	array('rmatch', 'hoster', 'cosmonova.net.ua', 'RBN.'),
	array('rmatch', 'hoster', 'borderfreehosting.com', 'RBN.'),
	array('rmatch', 'hoster', 'uxxicom.com', 'RBN.'),
	array('rmatch', 'hoster', 'starlogic.biz', 'RBN.'),
	array('rmatch', 'hoster', 'totalstat.ru', 'RBN.'),
	array('rmatch', 'hoster', 'hostrov.net', 'RBN.'),
	array('rmatch', 'hoster', 'nasza-klasa.pl', 'RBN.'),
	array('rmatch', 'hoster', 'datapoint.ru', 'RBN.'),
	array('rmatch', 'hoster', 'orange.sk', 'RBN.'),
	array('rmatch', 'hoster', 'cssgroup.lv', 'RBN.'),
	array('rmatch', 'hoster', 'odessa.ua', 'RBN.'),
	array('rmatch', 'hoster', 'profithost.net', 'RBN.'),
	array('rmatch', 'hoster', 'mtu-net.ru', 'RBN.'),
	array('rmatch', 'hoster', 'volia.ua', 'RBN.'),
	array('rmatch', 'hoster', 'nigma.ru', 'RBN.')
);

?>